version: '3.8'

services:

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: base_user_RE
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - network

  maven:
    build: .
    container_name: apiuserre
    ports:
      - "8082:8080"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - network
    links:
      - "mysql:database"

networks:
  network:

volumes:
  mysql_data: