name: Java CI/CD with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build Docker image
        run: docker build . -t my-dockerhub-username/my-java-app:latest

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push my-dockerhub-username/my-java-app:latest

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Docker Server
        env:
          SSH_CONNECTION_STRING: ${{ secrets.SSH_CONNECTION_STRING }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_CONNECTION_STRING }}" "docker-compose -f /path/to/your/docker-compose.yml down"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_CONNECTION_STRING }}" "docker-compose -f /path/to/your/docker-compose.yml pull apiuser"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_CONNECTION_STRING }}" "docker-compose -f /path/to/your/docker-compose.yml up -d"
